### ISSUE TITLE
Check that plugin folder is created before open it. 

### ISSUE THREAD

**Issue by Ric92** [mico-corp/mico#71]
mico: https://github.com/bardo91/mico/commit/bd0086a3343c7c716a66118c90ed0174f0561999
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::directory_iterator::construct: No such file or directory: "/home/grvc/.flow/plugins"

**Comment by Bardo91** [comment]
Why is this issue here? @Ric92 ... that happens in flow! https://github.com/mico-corp/flow

**Comment by Bardo91** [comment]
Fixed in flow
